# Default values for limesurvey.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: docker-cse.wds.io:5000/limesurvey
  tag: 0.1.1
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {
    kubernetes.io/ingress.class: nginx
  }
  path: /
  hosts:
    - survey.moviesanywhere.com
  tls:
    - secretName: moviesanywhere-com-tls
      hosts:
       - survey.moviesanywhere.com
